#!/bin/bash

DBFILENAME=db-backup-$(date +"%-Y-%-m-%-d-%-T")
DATAFILENAME=data-backup-$(date +"%-Y-%-m-%-d-%-T")
rsync -av --delete -e 'ssh -p 22' /.../.../srs user@server-ip:/root/backup-try/db/$DBFILENAME
rsync -av --delete -e 'ssh -p 22' /.../.../srs user@server-ip:/root/backup-try/data/$DATAFILENAME
# use ssh to backup your data in a remote server
# use rsa hey so your machine won't reqiure password 
# if you use a differnt ssh port just change it in the script
# add this command in crontab if you want to preform this task automaticlly
# sh /absluote-bath/this-bash-script
~                                
